# Generated by Django 5.1 on 2024-08-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('nomeFantasia', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
